# Configure main menu and social menu
[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100
  [main.params]
    icon = "home"

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = -50
  [main.params]
    icon = "home"

[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/ArborMathematica"
  params.icon = "brand-github"

[[social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  params.icon = "rss"

  # [[social]]
  #   identifier = "twitter"
  #   name = "Twitter"
  #   url = "https://twitter.com"
  #   params.icon = "brand-twitter"
