# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.ico"

[footer]
  since = 2024
  customText = ""

[dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
  compact = true
  subtitle = "大学数学を定理単位で解説"

  [sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.webp"

[article]
  headingAnchor = false
  math = true
  readingTime = true

## Widgets
[[widgets.homepage]]
  type = "search"

[[widgets.homepage]]
  type = "archives"
  params.limit = 5

[[widgets.homepage]]
  type = "categories"
  params.limit = 10

[[widgets.homepage]]
  type = "tag-cloud"
  params.limit = 10

[[widgets.page]]
  type = "toc"

[opengraph.twitter]
  site = ""
  card = "summary_large_image"

[defaultImage.opengraph]
  enabled = false
  local = false
  src = ""

[colorScheme]
  toggle = true
  default = "auto"

[imageProcessing.cover]
  enabled = true

[imageProcessing.content]
  enabled = true

## Comments
[comments]
  enabled = false
