title = "数学の樹"
baseURL = "https://arbormathematica.github.io/tree-of-math-project/"

timeZone = "Asia/Tokyo"

defaultContentLanguage = "ja"
languageCode = "ja"
hasCJKLanguage = true

theme = "dream"

enableGitInfo = true
disablePathToLower = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        escapedSpace = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  headerTitle = "数学の樹プロジェクト"
  motto = "大学数学を定理単位で解説"
  # description = ""
  siteStartYear = 2024

  # author = ""
  # email = "@gmail.com"
  avatar = "img/avatar.webp"
  favicon = "img/favicon.ico"

  lightTheme = "emerald"
  darkTheme = "forest"

  math = true
  rss = true
  stickyNav = true
  reorderNavItems = ["search", "posts", "categories", "tags"]
  collapseNavItems = ["posts", "rss"]
  noDefaultSummaryCover = true
  showTableOfContents = true
  showSummaryCoverInPost = true
  showPrevNextPost = true

  [params.advanced]
    customCSS = ["css/custom.css", "css/callout.css", "css/katex.css"]
    # customJS = []

  [params.experimental]
    jsDate = true
    jsDateFormat = "yyyy年M月d日"
