baseURL = "https://arbormathematica.github.io/tree-of-math-project/"
defaultContentLanguage = "ja"
languageCode = "ja"
title = "数学の樹"
theme = "dream"

hasCJKLanguage = true

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = ""
# backgroundImageDark = ""

# images = ["me/background.jpg"]

# author = ""
# description = ""
avatar = "img/avatar.webp"
headerTitle = "数学の樹プロジェクト"
motto = "大学数学を定理単位で解説"

rss = true

# email = "@gmail.com"

siteStartYear = 2024

favicon = "avatar.webp"

# options
stickyNav = true
reorderNavItems = ["search", "posts", "categories", "tags", "rss"]
collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true

# [params.navItems]
# github = { href = "https://github.com/g1eny0ung", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年M月d日"
