baseURL = "https://arbormathematica.github.io/tree-of-math-project/"
defaultContentLanguage = "ja"
languageCode = "ja"
title = "数学の樹"
theme = "dream"

hasCJKLanguage = true

[markup]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
math = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = ""
# backgroundImageDark = ""

# author = ""
# description = ""
avatar = "img/avatar.webp"
headerTitle = "数学の樹プロジェクト"
motto = "大学数学を定理単位で解説"

rss = true

# email = "@gmail.com"

siteStartYear = 2024

favicon = "img/favicon.ico"

# options
stickyNav = true
reorderNavItems = ["search", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags", "rss"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true

[params.advanced]
customCSS = ["css/custom.css", "css/callout.css", "css/katex.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年M月d日"
